# Generated by Django 5.0.3 on 2025-04-10 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_pawuser_receive_email_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oauth2User',
            fields=[
                ('paw_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('oauth2_id', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'OAuth2 User',
                'db_table': 'oauth2_user',
            },
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('de', 'German'), ('nl', 'Dutch')], default='en', max_length=2),
        ),
    ]
