# Generated by Django 5.0.3 on 2025-04-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_oauth2user_alter_mailtemplate_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='pawuser',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
